language: generic
sudo: false
branches:
 only:
 - master
 - develop
before_install:
- curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw
  > /tmp/x.sh && source /tmp/x.sh
- evm install $EVM_EMACS --use --skip
env:
 matrix:
 - FORMATTING=doc EVM_EMACS=emacs-25.2-travis TASK=formatting
 - TESTS=core EVM_EMACS=emacs-24.4-travis TASK=core
 global:
 - secure: "M8NF1Uw7VGkLdNmWiUF4T+VOJXwN8KCKVQb45/BWVpGm88Rcfom/9bxRTUme8VYuzIavph32QF+P9KyhX8aj2p2FMItNnxiEySzap5UrLrNiwB6ZxbQglMJj0yMQKASynNBai9KKI7mYlsM5jRpFJ9OSgj7Ko00RIFpO3EpJ+kE="
 - BOT_NAME=emacspace
 - BOT_EMAIL=emacspace@gmail.com
script: "./.travis-build.sh"

notifications:
  webhooks:
    urls:
      - https://spacemacs-pr-test.herokuapp.com/notifications
    on_success: always
    on_failure: always
    on_start: always
